### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by carreonjulius** [carreonjulius/SEBC#2]

**Comment by carreonjulius** [comment]
Created 5 m3.xlarge AWS instances with CentOS 6.5 operating system.

**Comment by mfernest** [comment]
How's the lab going for you?

**Comment by carreonjulius** [comment]
Hello Michael,

I have deployed my cluster already but I haven't uploaded the md files yet for the results.

**Comment by carreonjulius** [comment]
Hello Michael,

Now I have my cluster running green. Below is the list of the issues I have encountered during the installation.

**1. Starting cloudera-scm-server fails.**

I looked at the logs and it showed a Connection Refused error. After some searching, I found out that I haven't configured the **/etc/cloudera-scm-server/db.properties**. I edited it with the following parameters:

- com.cloudera.cmf.db.type
- com.cloudera.cmf.db.host
- com.cloudera.cmf.db.name
- com.cloudera.cmf.db.user
- com.cloudera.cmf.db.password
- com.cloudera.cmf.db.setupType


**2. Bad host health when adding a host into the cluster**

I see a bad host health when adding a host into the cluster. I checked the cloudera-scm-agent logs and found some lines showing a mismatch in cm_guid. I found an article on Cloudera's site named Know Issues and Workarounds suggesting to delete the cm_guid file. I've deleted it and restarted the cloudera-scm-agent service. Then, I was able to add the host to the cluster successfully.


**3. Clock offset bad**

I receive a clock offset error when I deployed the cluster. As per checking, the ntpd service on the data nodes wasn't enable at startup (I'm stopping the instances every end of the day). I enabled them and synced with the ntpd server installed on my CM host.

**Comment by mfernest** [comment]
You can edit `db.properties` directly, but you can also use the script `scm_prepare_database.sh` -- it's intended to validate access to the database server and write this file for you.

**Comment by carreonjulius** [comment]
Okay. I'll try again tonight while practicing for the challenge tomorrow. Thank you very much.

**Comment by mfernest** [comment]
👍
